Author.create(name: "N.K. Jemison")
Author.create(name: "Joe Abercrombie")
Author.create(name: "Kant")
Author.create(name: "Hobbs")
Author.create(name: "Hermin Mervile")
Author.create(name: "Dr. Seus")

Category.create(name: "Fantasy")
Category.create(name: "Philosophy")
Category.create(name: "Classics")
Category.create(name: "Children's")

Book.create(title: "The Fifth Season", category_id: 1, author_id: 1)
Book.create(title: "The Blade Itself", category_id: 1, author_id: 2)
Book.create(title: "Before They Are Hanged", category_id: 1, author_id: 2)
Book.create(title: "Last Argument of Kings", category_id: 1, author_id: 2)
Book.create(title: "Thoughts on the True Estimation of Living Forces", category_id: 2, author_id: 3)
Book.create(title: "Prolegomena to any Future Metaphysics", category_id: 2, author_id: 3)
Book.create(title: "Critique of Judgment", category_id: 2, author_id: 3)
Book.create(title: "Leviathan", category_id: 2, author_id: 4)
Book.create(title: "Merby Derk", category_id: 3, author_id: 5)
Book.create(title: "Oh The Places You'll Go", category_id: 4, author_id: 6)
Book.create(title: "Go Dogs Go", category_id: 4, author_id: 6)
Book.create(title: "The Lorax", category_id: 4, author_id: 6)
